version: "3.9"

services:
  sqlserver:
    build: ./database
    container_name: sqlserver_chn
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongPass1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - banco-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=SistemaPrestamos;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: StrongPass1!
    depends_on:
      - sqlserver
    networks:
      - banco-network

  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - banco-network

volumes:
  sql_data:

networks:
  banco-network:
    driver: bridge
