services:
  sqlserver:
    build: ./database
    container_name: sqlserver_chn
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "StrongPass1!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - sql_data:/var/opt/mssql

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=SistemaPrestamos;encrypt=false;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: StrongPass1!
    depends_on:
      - sqlserver

volumes:
  sql_data: 
